apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: smtp-source
spec:
  template:
    spec:
      containers:
        - image: direktiv/smtp-listener
          name: smtp
          imagePullPolicy: Always
          ports:
          - containerPort: 2525
          # env:
          # - name: POD_NAME
          #   value: "mypod"
          # - name: POD_NAMESPACE
          #   value: "event-test"
  sink:
    uri: http://direktiv-eventing.default/direktiv
---
apiVersion: v1 
kind: Service
metadata:
  name: smtp-listener-service
spec:
  selector:
    sources.knative.dev/containerSource: smtp-source
  ports:
    - port: 2525
